# Funding and Sponsorship Information

# This file specifies funding and sponsorship platforms for the project.
# Currently, sponsorship options are not configured, but this file is
# included for future use.

# Uncomment and configure the relevant platforms when ready:

# GitHub Sponsors
# github: [yourusername]

# Open Collective
# open_collective: wargames-joshua

# Ko-fi
# ko_fi: yourusername

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Patreon
# patreon: username

# Custom URL
# custom: ["https://your-sponsor-page.com"]

# Note: WarGames/JOSHUA is an open-source educational project.
# Sponsorship opportunities may be added in the future to support
# ongoing development, maintenance, and operational costs.

# For now, the best way to support the project is through:
# - Contributing code, documentation, or tests
# - Reporting bugs and suggesting improvements
# - Sharing the project with others interested in nuclear risk assessment
# - Participating in discussions and code reviews

# If you're interested in sponsoring this project, please open a discussion
# in the GitHub Discussions tab to discuss sponsorship options.
