name: Bug Report
description: Report a bug or unexpected behavior in WarGames/JOSHUA
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of WarGames/JOSHUA are you running?
      placeholder: "e.g., v0.1.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - CLI Interface
        - Data Collection Engine
        - Claude Analysis Engine
        - Risk Calculation Engine
        - Database Layer
        - Visualization Engine
        - Configuration System
        - Testing Framework
        - Documentation
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "e.g., rustc 1.75.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Specific OS version
      placeholder: "e.g., Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: |
        Relevant log output or error messages. Please use code blocks (```) to format.
        Run with `RUST_LOG=debug` for verbose logs.
      placeholder: |
        ```
        Paste error messages or logs here
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Relevant configuration settings (REMOVE ANY SENSITIVE DATA like API keys!)
      placeholder: |
        ```toml
        [general]
        # Your config here (with sensitive data removed)
        ```
      render: toml
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem. Screenshots, network traces, etc.
      placeholder: Add any additional context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have removed any sensitive information (API keys, passwords, etc.)
          required: true
        - label: I have provided steps to reproduce the issue
          required: true
        - label: I am using a supported version (see SECURITY.md)
          required: false
