name: Feature Request
description: Suggest a new feature or enhancement for WarGames/JOSHUA
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: |
        Is your feature request related to a problem? Please describe.
        What problem does this feature solve?
      placeholder: |
        I'm frustrated when...
        Currently it's difficult to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution you'd like. How should this feature work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Describe any alternative solutions or features you've considered.
        Why is your proposed solution better?
      placeholder: Alternative approaches...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component would this feature primarily affect?
      options:
        - CLI Interface
        - Data Collection Engine
        - Claude Analysis Engine
        - Risk Calculation Engine
        - Database Layer
        - Visualization Engine
        - Report Generation
        - Configuration System
        - Documentation
        - Multiple Components
        - New Component
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Related Development Phase
      description: Which development phase does this relate to?
      options:
        - Phase 0 - Foundation & Architecture
        - Phase 1 - Data Collection Engine
        - Phase 2 - Claude Analysis Engine
        - Phase 3 - Risk Calculation & Modeling
        - Phase 4 - Visualization & Reporting
        - Phase 5 - Integration & Testing
        - Phase 6 - Production Readiness
        - Future / Post-v1.0
        - Not phase-specific
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocks important use cases)
        - High (important but has workarounds)
        - Medium (nice to have, improves experience)
        - Low (minor improvement)
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: |
        Describe specific use cases for this feature.
        Who would benefit from this? How would they use it?
      placeholder: |
        1. User wants to...
        2. Analyst needs to...
    validations:
      required: false

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how to implement this feature, share them here.
        This could include technical approaches, API designs, UI mockups, etc.
      placeholder: Technical implementation ideas...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Projects
      description: |
        Are there similar features in other projects that could serve as inspiration?
        Include links or descriptions.
      placeholder: |
        - Project X does something similar by...
        - Reference: https://...
    validations:
      required: false

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: |
        Would this feature require breaking changes to existing APIs or behavior?
        How could we minimize disruption?
      placeholder: Potential breaking changes and migration strategies...
    validations:
      required: false

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Impact
      description: |
        What documentation would need to be created or updated?
      placeholder: Documentation requirements...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context, screenshots, mockups, or examples about the feature.
      placeholder: Additional context...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals (nuclear risk assessment)
          required: true
        - label: I have considered backward compatibility
          required: false
        - label: I am willing to help implement this feature
          required: false
